name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [24.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run validation tests
      run: npm test
    
    - name: Check code style
      run: npm run lint --if-present
    
    - name: Security audit
      run: npm audit --audit-level moderate
    
    - name: Generate test report
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ All tests passed successfully" >> $GITHUB_STEP_SUMMARY
        echo "📊 Setup validation completed" >> $GITHUB_STEP_SUMMARY
        echo "🔒 Security audit passed" >> $GITHUB_STEP_SUMMARY

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --production
    
    - name: Create deployment artifact
      run: |
        tar -czf whatsapp-me-bot.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=session \
          --exclude=data/backup \
          .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: whatsapp-me-bot
        path: whatsapp-me-bot.tar.gz
        retention-days: 30
